version: '3.8'
services:
  whatsapp-linker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - SERVER_URL=https://whapp.xia.ar/
      - SESSION_SECRET=eqieni12334ntwENE
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - NODE_ENV=production
      - ADMIN_USER=whapp-superuser
      - ADMIN_PASS=dnasd344mrewornDDD
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapp.rule=Host(`whapp.xia.ar`)"
      - "traefik.http.services.whatsapp.loadbalancer.server.port=3000"
